export const TIMELINE_EVENT_METADATA_VERSION = 1;

export const EVENT_TYPES = Object.freeze({
  PLAN_CREATED: 'PLAN_CREATED',
  STEP_COMPLETED: 'STEP_COMPLETED',
  PLAN_COMPLETED: 'PLAN_COMPLETED',

  FOLLOWUP_CREATED: 'FOLLOWUP_CREATED',
  FOLLOWUP_CANCELLED: 'FOLLOWUP_CANCELLED',

  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',

  VISIT_COMPLETED: 'VISIT_COMPLETED',

  ATTENTION_ACKNOWLEDGED: 'ATTENTION_ACKNOWLEDGED',
  ATTENTION_RESOLVED: 'ATTENTION_RESOLVED',
  ATTENTION_REOPENED: 'ATTENTION_REOPENED',

  MEDIA_UPLOADED: 'MEDIA_UPLOADED',
  OCR_ATTEMPTED: 'OCR_ATTEMPTED',
  OCR_COMPLETED: 'OCR_COMPLETED',
  OCR_FAILED: 'OCR_FAILED',
});
