export const FIXTURES = [
  {
    name: 'Patient Happy Path Booking',
    messages: [
      { text: 'Hi', intent: 'greeting' },
      { text: '1', intent: 'appointment' },
      { text: 'Tomorrow', intent: 'provide_date' },
      { text: '10am', intent: 'provide_time' },
      { text: 'Cleaning', intent: 'provide_treatment' },
      { text: 'ok', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'Patient Correction During Booking',
    messages: [
      { text: 'Hi', intent: 'greeting' },
      { text: 'Book appointment', intent: 'appointment' },
      { text: 'Tomorrow', intent: 'provide_date' },
      { text: 'Actually Wednesday', intent: 'correction_date' },
      { text: '2pm', intent: 'provide_time' },
      { text: 'Root canal', intent: 'provide_treatment' },
      { text: 'ok', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'Patient Invalid Then Corrected',
    messages: [
      { text: 'Hi', intent: 'greeting' },
      { text: 'Book', intent: 'appointment' },
      { text: 'Banana', intent: 'unknown' },
      { text: 'Tomorrow', intent: 'provide_date' },
      { text: "O'clock", intent: 'unknown' },
      { text: '10am', intent: 'provide_time' },
      { text: 'Zebra', intent: 'unknown' },
      { text: 'General Dentistry', intent: 'provide_treatment' },
      { text: 'ok', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'Patient Menu Interruption and Resume',
    messages: [
      { text: 'Hi', intent: 'greeting' },
      { text: 'Book', intent: 'appointment' },
      { text: 'Tomorrow', intent: 'provide_date' },
      { text: 'Menu', intent: 'main_menu' },
      { text: 'Book', intent: 'appointment' },
      { text: 'Next Monday', intent: 'provide_date' },
      { text: '10am', intent: 'provide_time' },
      { text: 'Root Canal', intent: 'provide_treatment' },
      { text: 'ok', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'Patient Escalation During Booking',
    messages: [
      { text: 'Hi', intent: 'greeting' },
      { text: 'Book', intent: 'appointment' },
      { text: 'Tomorrow', intent: 'provide_date' },
      { text: 'Talk to agent', intent: 'escalate' },
    ],
    expectations: { finalState: 'HUMAN_ESCALATION' },
  },
  {
    name: 'Patient Cancel During Booking',
    messages: [
      { text: 'Hi', intent: 'greeting' },
      { text: 'Book', intent: 'appointment' },
      { text: 'Tomorrow', intent: 'provide_date' },
      { text: 'Nevermind', intent: 'cancel' },
    ],
    expectations: { finalState: 'MAIN_MENU' },
  },
  {
    name: 'Patient Callback Flow',
    messages: [
      { text: 'Hi', intent: 'greeting' },
      { text: 'Callback', intent: 'callback' },
      { text: '9876543210', intent: 'provide_phone' },
    ],
    expectations: { finalState: 'MAIN_MENU' },
  },
  {
    name: 'Doctor Greeting to Main Menu',
    role: 'doctor',
    messages: [
      { text: 'Hi', intent: 'greeting' },
    ],
    expectations: { finalState: 'DOCTOR_MAIN_MENU' },
  },
  {
    name: 'Doctor View Today (Positive)',
    role: 'doctor',
    messages: [
      { text: 'Hi', intent: 'greeting' },
      { text: "Today's Appointments", type: 'interactive', interactiveId: 'doc_today', intent: 'doctor_view_today' },
    ],
    expectations: { finalState: 'DOCTOR_APPOINTMENT_LIST' },
  },
  {
    name: 'Doctor Manage Schedule (Positive)',
    role: 'doctor',
    messages: [
      { text: 'Hi', intent: 'greeting' },
      { text: 'Manage Schedule', type: 'interactive', interactiveId: 'doc_schedule', intent: 'doctor_manage_schedule' },
    ],
    expectations: { finalState: 'DOCTOR_MANAGE_SCHEDULE' },
  },
  {
    name: 'Doctor Stats (Positive)',
    role: 'doctor',
    messages: [
      { text: 'Back', type: 'interactive', interactiveId: 'back', intent: 'back' },
      { text: 'View Stats', type: 'interactive', interactiveId: 'doc_stats', intent: 'doctor_view_stats' },
    ],
    expectations: { finalState: 'DOCTOR_STATS' },
  },
  {
    name: 'Doctor Invalid Date Input (Negative)',
    role: 'doctor',
    messages: [
      { text: 'Back', type: 'interactive', interactiveId: 'back', intent: 'back' },
      { text: 'View by Date', type: 'interactive', interactiveId: 'doc_by_date', intent: 'doctor_view_by_date' },
      { text: 'banana', intent: 'unknown' },
    ],
    expectations: { finalState: 'DOCTOR_VIEW_DATE' },
  },
  {
    name: 'Doctor Unknown Input Stays Menu (Negative)',
    role: 'doctor',
    messages: [
      { text: 'Back', type: 'interactive', interactiveId: 'back', intent: 'back' },
      { text: 'abracadabra', intent: 'unknown' },
    ],
    expectations: { finalState: 'DOCTOR_MAIN_MENU' },
  },
  {
    name: 'India Date Ambiguity Guard (kal)',
    messages: [
      { text: 'Hi', intent: 'greeting' },
      { text: 'book', intent: 'appointment' },
      { text: 'kal', intent: 'unknown' },
    ],
    expectations: { finalState: 'BOOKING_COLLECTION' },
  },
  {
    name: 'India Hindi Time Parsing (baje)',
    messages: [
      { text: 'Hi', intent: 'greeting' },
      { text: 'book', intent: 'appointment' },
      { text: 'tomorrow', intent: 'provide_date' },
      { text: '5 baje shaam', intent: 'provide_time' },
      { text: 'cleaning', intent: 'provide_treatment' },
      { text: 'haan', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'India Hindi Date Parsing (parso)',
    messages: [
      { text: 'hi', intent: 'greeting' },
      { text: 'book', intent: 'appointment' },
      { text: 'parso', intent: 'provide_date' },
      { text: '10am', intent: 'provide_time' },
      { text: 'root canal', intent: 'provide_treatment' },
      { text: 'ok', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'India Relative Days Parsing (do din baad)',
    messages: [
      { text: 'hi', intent: 'greeting' },
      { text: 'book', intent: 'appointment' },
      { text: 'do din baad', intent: 'provide_date' },
      { text: '11am', intent: 'provide_time' },
      { text: 'cleaning', intent: 'provide_treatment' },
      { text: 'haan', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'India Hinglish Time Parsing (saade 5)',
    messages: [
      { text: 'hi', intent: 'greeting' },
      { text: 'book', intent: 'appointment' },
      { text: 'tomorrow', intent: 'provide_date' },
      { text: 'saade 5', intent: 'provide_time' },
      { text: 'general checkup', intent: 'provide_treatment' },
      { text: 'theek hai', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'India Emergency Phrase (masoodon se khun)',
    messages: [
      { text: 'masoodon se khun aa raha hai', intent: 'emergency' },
    ],
    expectations: { finalState: 'MAIN_MENU' },
  },
  {
    name: 'India Cancel Confirm Hindi No (mat karo)',
    messages: [
      { text: 'hi', intent: 'greeting' },
      { text: 'book', intent: 'appointment' },
      { text: 'tomorrow', intent: 'provide_date' },
      { text: '10am', intent: 'provide_time' },
      { text: 'cleaning', intent: 'provide_treatment' },
      { text: 'ok', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
      { text: 'cancel', intent: 'cancel' },
      { text: 'mat karo', intent: 'back' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'India Mixed Language Booking (tomorrow + bje + haan)',
    messages: [
      { text: 'namaste', intent: 'greeting' },
      { text: 'book appointment', intent: 'appointment' },
      { text: 'tomorrow', intent: 'provide_date' },
      { text: '6 bje', intent: 'provide_time' },
      { text: 'general checkup', intent: 'provide_treatment' },
      { text: 'haan', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'India Callback Invalid Then Valid Phone',
    messages: [
      { text: 'hi', intent: 'greeting' },
      { text: 'callback', intent: 'callback' },
      { text: '1234567890', intent: 'unknown' },
      { text: '9876543210', intent: 'provide_phone' },
    ],
    expectations: { finalState: 'MAIN_MENU' },
  },
  {
    name: 'India Emergency Hinglish Phrase (bahut dard)',
    messages: [
      { text: 'bahut dard ho raha hai', intent: 'emergency' },
    ],
    expectations: { finalState: 'MAIN_MENU' },
  },
  {
    name: 'India Relative Days Numeric (3 din baad)',
    messages: [
      { text: 'hi', intent: 'greeting' },
      { text: 'book', intent: 'appointment' },
      { text: '3 din baad', intent: 'provide_date' },
      { text: '2pm', intent: 'provide_time' },
      { text: 'root canal', intent: 'provide_treatment' },
      { text: 'ok', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'India Devanagari Date Time (आज + ५ बजे शाम)',
    messages: [
      { text: 'नमस्ते', intent: 'greeting' },
      { text: 'book', intent: 'appointment' },
      { text: 'आज', intent: 'provide_date' },
      { text: '५ बजे शाम', intent: 'provide_time' },
      { text: 'cleaning', intent: 'provide_treatment' },
      { text: 'हाँ', intent: 'affirm' },
      { text: 'confirm', intent: 'confirm' },
    ],
    expectations: { finalState: 'BOOKED' },
  },
  {
    name: 'India Devanagari Emergency (बहुत दर्द)',
    messages: [
      { text: 'बहुत दर्द हो रहा है', intent: 'emergency' },
    ],
    expectations: { finalState: 'MAIN_MENU' },
  },
];
