export const GLOBAL_INTENTS = {
  language_en: ['english','speak english','in english','english please'],
  language_hi: ['hindi','speak hindi','in hindi','hinglish','hindi me','hindi mein'],
  emergency: ['emergency','pain','bleeding','swelling','accident','urgent',
              'toothache','abscess','fracture','knocked out','severe','hurts','broken tooth','injury',
              'khun','khoon','dard','soojan','sujan','tez dard','bahut dard','bahot dard','masoodon se khun',
              'खून','दर्द','तेज दर्द','बहुत दर्द'],
  cancel:    ['cancel','forget it','abort','nevermind','never mind','radd karo','cancel karo','रद्द','कैंसल'],
  main_menu: ['0','menu','home','start over','restart','main menu','back to menu'],
  escalate:  ['agent','human','talk to','representative','speak to','person'],
  back:      ['back','previous','go back','return'],
  affirm:    ['ok','okay','sure','right','fine','good','yep','yeah','alright','that works','perfect','great','got it','cool','done with this','haan','han','thik hai','theek hai','kar do','हाँ','ठीक है','कर दो','हां'],
  arrival:   ['arrived',"i'm here","i've arrived","i have arrived","i am here",'im here','reached','i reached','i have reached',
               'pahunch gaya','pahunch gya','aa gaya','aa gya','pahunch gaye','pohoch gaya','aa gaye'],
  greeting:  ['hi','hello','hey','namaste','good morning','good afternoon','good evening','नमस्ते'],
  thanks:    ['thanks','thank you','thx','ty','appreciate'],
  help:      ['help','?','what can you do'],
};

export const CORRECTION_INTENTS = [
  'correction_date',
  'correction_time',
  'correction_treatment',
];

export const STATE_INTENTS = {
  MAIN_MENU:            { appointment: ['1','book','appointment','book appointment','schedule a visit','booking','schedule'],
                          services:    ['2','services','dental services','treatment','procedures','what we offer','what do you do'],
                          location:    ['3','location','clinic location','address','directions','where'],
                          timings:     ['4','timings','clinic timings','hours','open','close','schedule'],
                          my_appointments: ['5','my appointments','my bookings','upcoming appointments','appointments',"cancel my appointment","reschedule","manage appointment"],
                          callback:    ['callback','call back','call me back','ring me'] },
  BOOKING_COLLECTION:   { correction_date:   ['actually','change date','different date'],
                          correction_time:   ['actually','change time','different time','evening','morning','afternoon'],
                          correction_treatment: ['not','actually','different treatment','not that'] },
  BOOKING_CONFIRMATION: { confirm:    ['confirm','correct','book it','done','proceed','yes','go ahead','book','haan','han','thik hai','theek hai','kar do','हाँ','ठीक है','कर दो'],
                          edit_date:  ['change date','different date','date'],
                          edit_time:  ['change time','different time','time'] },
  BOOKED:               { appointment: ['book another','book','1'],
                          main_menu:   ['menu','0','done'],
                          cancel_appointment: ['cancel appointment','cancel this','cancel my appointment'],
                          reschedule: ['reschedule','change appointment','change date','change time','rebook'] },
  CANCEL_CONFIRM:       { confirm_cancel: ['yes','confirm','cancel it','yes cancel','haan','han','radd karo','cancel karo','हाँ','रद्द करो','कैंसल करो'],
                          back:         ['no','keep','back','dont cancel','nahi','mat karo','cancel mat karo','नहीं','मत करो'] },
  DOCTOR_APPOINTMENT_DETAIL: { doctor_mark_completed: ['done','complete','finished','mark done','completed'],
                               doctor_mark_noshow:    ['no show',"didn't come","did not come","missed","noshow"] },
  DOCTOR_MAIN_MENU: { doctor_view_queue: ['queue','waiting','line','next patient'] },
  DOCTOR_EDIT_PATIENT: { provide_name: ['name','edit name','change name'],
                          provide_age: ['age','edit age','change age'],
                          provide_sex: ['sex','edit sex','change sex'] },
};