export const STATES = [
  'IDLE','MAIN_MENU','BOOKING_COLLECTION',
  'BOOKING_CONFIRMATION','BOOKED','SERVICES','LOCATION','TIMINGS',
  'EMERGENCY','HUMAN_ESCALATION','CALLBACK_REQUESTED','CANCEL_CONFIRM',
  'DONE','ABANDONED',
  'DOCTOR_MAIN_MENU','DOCTOR_VIEW_DATE','DOCTOR_APPOINTMENT_LIST',
  'DOCTOR_APPOINTMENT_DETAIL','DOCTOR_MANAGE_SCHEDULE','DOCTOR_STATS',
  'REGISTER_NAME','REGISTER_AGE','REGISTER_SEX','REGISTER_PHONE','REGISTER_APPOINTMENT',
  'LOG_TREATMENT','LOG_CONSULTATION_FEE','LOG_TREATMENT_CHARGES','LOG_MEDICINE_CHARGES',
  'LOG_NEXT_VISIT','LOG_NOTES','LOG_MEDIA','DOCTOR_SEARCH_PATIENT','DOCTOR_VIEW_CHIT',
  'DOCTOR_PATIENT_VISITS','DOCTOR_EDIT_PATIENT','DOCTOR_FEEDBACK',
  'DOCTOR_LOG_VISIT_NAME',
  'FAMILY_SELECTION',
  'RECEPTIONIST_MAIN_MENU','RECEPTIONIST_VIEW_QUEUE','RECEPTIONIST_QUEUE_DETAIL','DOCTOR_VIEW_QUEUE',
];

export const TRANSITIONS = {
  IDLE:                 ['greeting','appointment','services','location','timings','emergency','escalate'],
  MAIN_MENU:            ['appointment','services','location','timings','emergency','escalate','callback'],
  BOOKING_COLLECTION:   ['provide_date','provide_time','provide_treatment','cancel','emergency','escalate','back',
                          'correction_date','correction_time','correction_treatment',
                          'affirm','date_custom','date_more','time_custom','treatment_help'],
  BOOKING_CONFIRMATION: ['confirm','edit_date','edit_time','edit_treatment','cancel','emergency','escalate'],
  BOOKED:               ['appointment','cancel_appointment','reschedule','main_menu','emergency','escalate'],
  SERVICES:             ['appointment','main_menu','emergency','escalate'],
  LOCATION:             ['main_menu','emergency','escalate'],
  TIMINGS:              ['main_menu','emergency','escalate'],
  EMERGENCY:            ['main_menu','escalate'],
  HUMAN_ESCALATION:     ['main_menu'],
  CALLBACK_REQUESTED:   ['provide_phone','cancel','emergency','escalate'],
  CANCEL_CONFIRM:       ['confirm_cancel','back','main_menu','emergency','escalate'],
  ABANDONED:            ['main_menu','greeting'],
  DONE:                 ['main_menu','greeting'],
  DOCTOR_MAIN_MENU:     ['doctor_view_today','doctor_view_by_date','doctor_manage_schedule',
                          'doctor_view_stats','doctor_register_patient','doctor_search_patient',
                          'doctor_view_queue','doctor_call_next',
                          'emergency','escalate','back','greeting'],
  DOCTOR_VIEW_DATE:     ['provide_date','date_custom','back','emergency','escalate'],
  DOCTOR_APPOINTMENT_LIST: ['doctor_appt_detail','back','emergency','escalate'],
  DOCTOR_APPOINTMENT_DETAIL: ['doctor_mark_completed','doctor_mark_noshow','back','emergency','escalate'],
  DOCTOR_MANAGE_SCHEDULE: ['doctor_block_date','doctor_view_blocked','block_cancel_all','block_notify_reschedule','back','emergency','escalate'],
  DOCTOR_STATS:         ['back','emergency','escalate'],
  REGISTER_NAME:        ['provide_name','back','emergency','escalate'],
  REGISTER_AGE:         ['provide_age','back','emergency','escalate'],
  REGISTER_SEX:         ['provide_sex','back','emergency','escalate'],
  REGISTER_PHONE:       ['provide_phone','back','emergency','escalate'],
  REGISTER_APPOINTMENT: ['provide_appointment_time','walk_in','back','emergency','escalate'],
  LOG_TREATMENT:        ['provide_log_treatment','back','emergency','escalate'],
  LOG_CONSULTATION_FEE: ['provide_fee','back','emergency','escalate'],
  LOG_TREATMENT_CHARGES: ['provide_fee','back','emergency','escalate'],
  LOG_MEDICINE_CHARGES: ['provide_fee','back','emergency','escalate'],
  LOG_NEXT_VISIT:       ['provide_next_visit','no_next_visit','back','emergency','escalate'],
  LOG_NOTES:            ['provide_notes','no_notes','back','emergency','escalate'],
  LOG_MEDIA:            ['provide_media','skip_media','back','emergency','escalate'],
  DOCTOR_SEARCH_PATIENT: ['provide_search_query','select_patient','back','emergency','escalate'],
  DOCTOR_VIEW_CHIT:      ['view_media','back','emergency','escalate'],
  DOCTOR_PATIENT_VISITS: ['doctor_appt_detail','doctor_edit_patient','back','emergency','escalate'],
  DOCTOR_EDIT_PATIENT: ['provide_name','provide_age','provide_sex','back','emergency','escalate'],
  DOCTOR_FEEDBACK: ['back','emergency','escalate'],
  DOCTOR_LOG_VISIT_NAME: ['provide_search_query','select_patient','back','emergency','escalate'],
  RECEPTIONIST_MAIN_MENU: ['receptionist_view_queue','receptionist_register_walkin',
                            'receptionist_search','back','emergency','escalate','greeting'],
  RECEPTIONIST_VIEW_QUEUE: ['receptionist_queue_patient','back','emergency','escalate'],
  RECEPTIONIST_QUEUE_DETAIL: ['queue_mark_called','queue_toggle_priority','back','emergency','escalate'],
  DOCTOR_VIEW_QUEUE: ['doctor_call_next','doctor_call_patient','back','emergency','escalate'],
  FAMILY_SELECTION: ['select_family_patient','back','emergency','escalate'],
};
