export const STATES = [
  'IDLE','MAIN_MENU','BOOKING_COLLECTION',
  'BOOKING_CONFIRMATION','BOOKED','SERVICES','LOCATION','TIMINGS',
  'EMERGENCY','HUMAN_ESCALATION','CALLBACK_REQUESTED','CANCEL_CONFIRM',
  'DONE','ABANDONED',
  'DOCTOR_MAIN_MENU','DOCTOR_VIEW_DATE','DOCTOR_APPOINTMENT_LIST',
  'DOCTOR_APPOINTMENT_DETAIL','DOCTOR_MANAGE_SCHEDULE','DOCTOR_STATS',
];

export const TRANSITIONS = {
  IDLE:                 ['greeting','appointment','services','location','timings','emergency','escalate'],
  MAIN_MENU:            ['appointment','services','location','timings','emergency','escalate','callback'],
  BOOKING_COLLECTION:   ['provide_date','provide_time','provide_treatment','cancel','emergency','escalate','back',
                          'correction_date','correction_time','correction_treatment',
                          'affirm','date_custom','date_more','time_custom','treatment_help'],
  BOOKING_CONFIRMATION: ['confirm','edit_date','edit_time','edit_treatment','cancel','emergency','escalate'],
  BOOKED:               ['appointment','cancel_appointment','reschedule','main_menu','emergency','escalate'],
  SERVICES:             ['appointment','main_menu','emergency','escalate'],
  LOCATION:             ['main_menu','emergency','escalate'],
  TIMINGS:              ['main_menu','emergency','escalate'],
  EMERGENCY:            ['main_menu','escalate'],
  HUMAN_ESCALATION:     ['main_menu'],
  CALLBACK_REQUESTED:   ['provide_phone','cancel','emergency','escalate'],
  CANCEL_CONFIRM:       ['confirm_cancel','back','main_menu','emergency','escalate'],
  ABANDONED:            ['main_menu','greeting'],
  DONE:                 ['main_menu','greeting'],
  DOCTOR_MAIN_MENU:     ['doctor_view_today','doctor_view_by_date','doctor_manage_schedule',
                          'doctor_view_stats','emergency','escalate','back','greeting'],
  DOCTOR_VIEW_DATE:     ['provide_date','date_custom','back','emergency','escalate'],
  DOCTOR_APPOINTMENT_LIST: ['doctor_appt_detail','back','emergency','escalate'],
  DOCTOR_APPOINTMENT_DETAIL: ['doctor_mark_completed','doctor_mark_noshow','back','emergency','escalate'],
  DOCTOR_MANAGE_SCHEDULE: ['doctor_block_date','doctor_view_blocked','back','emergency','escalate'],
  DOCTOR_STATS:         ['back','emergency','escalate'],
};
